### ISSUE TITLE
New version 4.10.3 breaks controller support

### ISSUE THREAD

**Issue by Ericchi** [marzent/XIV-on-Mac#134]
I had to downgrade because my controller was not detected anymore after the update.
I am using an 8bitdo SN30 in XInput mode. I also tried it in basic mode and it doesn't work as well.

**Comment by seathasky** [comment]
Thanks for the heads up, we're looking into it.

**Comment by wevtimoteo** [comment]
> I had to downgrade because my controller was not detected anymore after the update. I am using an 8bitdo SN30 in XInput mode. I also tried it in basic mode and it doesn't work as well.

Just to provide more details, I'm also affected, using [GuliKit KingKong 2 Pro Controller](https://www.gulikit.com/productinfo/737791.html) also in XInput.

**Comment by seathasky** [comment]
It's an SDL issue with the latest wine we pushed, should be fixed next xom release

**Comment by wevtimoteo** [comment]
> It's an SDL issue with the latest wine we pushed, should be fixed next xom release

Thanks for the investigation!

**Comment by wevtimoteo** [comment]
For those who already launched the game on v4.10.3, and reverted to `v4.10.2` as @seathasky suggested, remember to open `Activity Monitor` and `Force quit` all `wine*` processes. Otherwise, your `XIVMac` will still not recognizing the gamepad.

**Comment by wevtimoteo** [comment]
Update: `v4.10.4` solved the issue for me! 🎉 Nice job, everyone!
